if(model.copiaSolicitante==1){
model.cpfcnpj1=model.cpfcnpj2;
model.nome1=model.nome2;
model.rg=model.rgSol;
model.celularTelefone=model.telefoneSol;
model.endereco1=model.enderecoSol;
model.numero1=model.numeroSol;
model.complemento1=model.complementoSol;
model.bairro1=model.bairroSol;
model.cidade1=model.cidadeSol;
model.email1=model.emailSol;
model.cdSujeito1=model.cdSujeito2;
model.tpPessoa1=model.tpPessoaSol;
}
else {
model.cpfcnpj1="";
model.nome1="";
model.rg="";
model.celularTelefone="";
model.endereco1="";
model.numero1="";
model.complemento1="";
model.bairro1="";
model.cidade1="";
model.email1="";
model.cdSujeito1="";
model.tpPessoa1="F";
}
